### ISSUE TITLE
Add support for Xenial

### ISSUE THREAD

**Issue by edmorley** [travis-ci/perl-builder#3]
Placeholder issue to link to from the TODO being added by travis-ci/packer-templates#549.

**Comment by edmorley** [comment]
I'm getting 404s for these archives on the latest Opal builds:
https://s3.amazonaws.com/travis-perl-archives/binaries/ubuntu/16.04/x86_64/perl-5.22-extras.tar.bz2
https://s3.amazonaws.com/travis-perl-archives/binaries/ubuntu/16.04/x86_64/perl-5.24-extras.tar.bz2

@BanzaiMan, is there something else that needs to happen for this file to be available?

_Edit:_ I'm guessing something like the following needs to be run?
`VERSION=perl-5.22.0 NAME=5.22-extras ALIAS=5.22-shrlibs ARGS='-Duseshrplib -Duseithreads'`
and
`VERSION=perl-5.24.0 NAME=5.24-extras ALIAS=5.24-shrlibs ARGS='-Duseshrplib -Duseithreads'`

**Comment by BanzaiMan** [comment]
* https://travis-ci.org/travis-ci/perl-builder/builds/309161291
* https://travis-ci.org/travis-ci/perl-builder/builds/309161366

**Comment by edmorley** [comment]
Many thanks - working great :-)
https://travis-ci.org/travis-infrastructure/packer-build/jobs/309649067#L2234
