### ISSUE TITLE
Add support for osx_image: xcode8.3

### ISSUE THREAD

**Issue by kiwiroy** [travis-ci/perl-builder#5]
The matrix is currently commented 😞 

https://github.com/travis-ci/perl-builder/blob/a688863174e61974816e334eff885953ddb4a1c8/.travis.yml#L30-L33

**Comment by BanzaiMan** [comment]
Those were failing. https://github.com/travis-ci/perl-builder/commit/5c5f08c2a678acbb7cfe1688433b12a6ccdc53a9 (see https://www.travis-ci.org/travis-ci/perl-builder/builds/239804014 for the last attempt) and we don't support Perl on Mac at this time, either. https://github.com/travis-ci/travis-ci/issues/2314

I'm sorry to say, but it is unlikely to be looked at.

**Comment by kiwiroy** [comment]
Thanks for the quick reply and the explanatory links.

Here's my [experiment](https://github.com/kiwiroy/travis-osx-perl/blob/master/.travis.yml) and [build](https://travis-ci.org/kiwiroy/travis-osx-perl/builds/349763479) and conclusion that 5.20+ are currently still available in aws buckets.

How long before 10.11/xcode7.3 goes away?
